# Generated by Django 5.0.6 on 2024-06-27 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fellowship',
            name='Duration',
        ),
        migrations.AddField(
            model_name='fellowship',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
